default: &default
  adapter: "postgresql"
  host: "containers-us-west-83.railway.app"
  username: "postgres"
  password: "ZIR5iuQ1ICk7eu2AwSec"
  port: 5771

development:
  <<: *default
  database: railway

test:
  <<: *default
  database: albums_test

production:
  <<: *default
  database: railway
